import { CerebriConsumerError, record, type DecodedResult } from './contracts'

export type RustReason = Readonly<{ code: string; source: 'validation' | 'rejection' | 'candidate' }>
const fail = (): never => { throw new CerebriConsumerError('invalid_response') }
const validationUnits = new Set(['UnsupportedSchema', 'PlanningPermissionDenied', 'NoTargets', 'UnsupportedSearchBudget', 'UnsupportedTargetCount', 'InputLimit', 'IncompleteCoverage'])
const validationIds = new Set(['UnsupportedObject', 'DuplicateObject', 'DuplicateFact', 'DuplicateTarget', 'UnknownObject', 'ContradictoryFact', 'InvalidFactSource', 'ScopeViolation', 'MissingPlanningCapability', 'PolicyDenied', 'InvalidTargetState'])
const required = new Set(['Missing', 'Unknown', 'Uncertain', 'Ambiguous', 'Unresolved'])
const violations = new Set(['Overlap', 'OutsideBounds', 'WrongDuration', 'DependencyMissing', 'DependencyOrder', 'InsufficientBuffer', 'TimezoneMismatch', 'Locked', 'UnsupportedRecurrence'])
const textId = (v: unknown) => typeof v === 'string' && /^[A-Za-z0-9._-]{1,128}$/.test(v)
const tagged = (v: unknown): [string, unknown] => record(v) && Object.keys(v).length === 1 ? Object.entries(v)[0] : fail()
const fields = (v: unknown, names: string[]): v is Record<string, unknown> => record(v) && Object.keys(v).length === names.length && names.every(n => Object.prototype.hasOwnProperty.call(v, n))
function validationCode(value: unknown): string {
  if (typeof value === 'string') return validationUnits.has(value) ? value : fail()
  const [code, data] = tagged(value)
  if (validationIds.has(code) && textId(data)) return code
  if (code === 'UnsupportedOperation' && ['CREATE', 'MOVE', 'UPDATE', 'CANCEL', 'FIND_SLOT', 'RESCHEDULE', 'OPTIMIZE', 'PLAN', 'ANALYZE'].includes(String(data))) return code
  if (code === 'RequiredDuration' && required.has(String(data))) return `${code}.${data}`
  if (code === 'RequiredTime' && fields(data, ['object_id', 'reason']) && textId(data.object_id) && required.has(String(data.reason))) return `${code}.${data.reason}`
  // N2 translates only the bounded N1 profile's reasons. Unimplemented payload
  // variants (Compilation/Dependency) fail closed instead of inventing explanations.
  return fail()
}
function rejectionCode(value: unknown): string {
  if (typeof value === 'string') return ['MutationLimit', 'MovedObjectLimit', 'InvalidTargets'].includes(value) ? value : fail()
  const [code, data] = tagged(value)
  if (['Scope', 'InvalidDuration', 'Capability', 'Policy'].includes(code) && textId(data)) return code
  if (code === 'HardConstraint' && fields(data, ['constraint', 'object_id', 'reason', 'evidence'])
    && textId(data.object_id) && violations.has(String(data.reason)) && record(data.constraint) && record(data.evidence)) return `${code}.${data.reason}`
  return fail()
}
function candidateCode(value: unknown): string {
  if (typeof value === 'string') return ['FeasibleWithinScope', 'EarliestTieBreak', 'AnalysisOnly', 'DurationUncertain'].includes(value) ? value : fail()
  const [code, data] = tagged(value)
  // PreferredStart is not generated by the N1 adapter (its preferences are empty).
  return code === 'PreferredStart' && ['ExplicitCurrentRequest', 'SessionContext', 'PersonalLearned', 'GlobalLearned', 'Default'].includes(String(data)) ? `${code}.${data}` : fail()
}
/** Enum spellings from Rust 1e1ecd6; no raw messages or learned explanation. */
export function previewReasons(result: Extract<DecodedResult, { status: 'planned' }>): RustReason[] {
  const evidence = result.evidence
  if (!record(evidence.validation) || !Array.isArray(evidence.validation.issues) || !record(evidence.conflicts) || !Array.isArray(evidence.conflicts.rejections)) return fail()
  const reasons: RustReason[] = [], seen = new Set<string>()
  const add = (source: RustReason['source'], code: string) => { const key = `${source}:${code}`; if (!seen.has(key)) { seen.add(key); reasons.push({ source, code }) } }
  evidence.validation.issues.forEach(value => add('validation', validationCode(value)))
  evidence.conflicts.rejections.forEach(value => {
    if (!record(value) || !Array.isArray(value.reasons)) return fail()
    value.reasons.forEach(reason => add('rejection', rejectionCode(reason)))
  })
  result.candidates.forEach(candidate => {
    if (!Array.isArray(candidate.evidence.explanation)) return fail()
    candidate.evidence.explanation.forEach(component => {
      if (!fields(component, ['reason', 'cost']) || typeof component.cost !== 'number' || !Number.isSafeInteger(component.cost) || component.cost < 0) return fail()
      add('candidate', candidateCode(component.reason))
    })
  })
  return reasons
}
