export const EDITOR_COMMAND_CATEGORY_ORDER = Object.freeze([
  "file",
  "navigation",
  "symbols",
  "source-control",
  "diagnostics",
  "terminal",
  "layout",
  "extensions",
  "preferences",
]);

export const EDITOR_COMMAND_CATEGORIES = Object.freeze({
  file: Object.freeze({
    id: "file",
    label: "Files",
    description: "Dateien und Workspaces",
    tone: "cyan",
  }),
  navigation: Object.freeze({
    id: "navigation",
    label: "Search & Navigation",
    description: "Dateien, Symbole und Fokus finden",
    tone: "sky",
  }),
  symbols: Object.freeze({
    id: "symbols",
    label: "Symbols",
    description: "Scopes, Klassen und Funktionen",
    tone: "violet",
  }),
  "source-control": Object.freeze({
    id: "source-control",
    label: "Git & GitHub",
    description: "Branches, Reviews und Aenderungen",
    tone: "sky",
  }),
  diagnostics: Object.freeze({
    id: "diagnostics",
    label: "Problems",
    description: "Fehler, Warnungen und Lint-Hinweise",
    tone: "violet",
  }),
  terminal: Object.freeze({
    id: "terminal",
    label: "Terminal & Tasks",
    description: "Shells, Scripts und Build-Flows",
    tone: "cyan",
  }),
  layout: Object.freeze({
    id: "layout",
    label: "Layout",
    description: "Panels, Fokus und Raum",
    tone: "violet",
  }),
  extensions: Object.freeze({
    id: "extensions",
    label: "Extensions",
    description: "Sprachtools, Formatter und Integrationen",
    tone: "cyan",
  }),
  preferences: Object.freeze({
    id: "preferences",
    label: "Settings",
    description: "Editor, Theme und Account",
    tone: "sky",
  }),
});

export const EDITOR_COMMANDS = Object.freeze([
  Object.freeze({
    id: "new-file",
    actionId: "new-file",
    label: "Neue Datei erstellen",
    description: "Lege eine neue TypeScript-Datei im aktuellen Workspace an.",
    category: "file",
    shortcut: "Ctrl+N",
    keywords: Object.freeze(["create", "file", "datei", "typescript", "javascript", "new"]),
    surfaces: Object.freeze(["palette", "spotlight"]),
    priority: 100,
  }),
  Object.freeze({
    id: "open-folder",
    actionId: "open-folder",
    label: "Workspace-Ordner oeffnen",
    description: "Waehle einen lokalen Projektordner aus.",
    category: "file",
    shortcut: "Ctrl+O",
    keywords: Object.freeze(["folder", "workspace", "project", "ordner", "open"]),
    surfaces: Object.freeze(["palette", "spotlight"]),
    priority: 96,
  }),
  Object.freeze({
    id: "open-explorer",
    actionId: "open-explorer",
    label: "Explorer anzeigen",
    description: "Oeffne den Datei-Explorer der Workbench.",
    category: "navigation",
    shortcut: "Ctrl+B",
    keywords: Object.freeze(["files", "sidebar", "tree", "explorer", "project", "navigation", "browse"]),
    surfaces: Object.freeze(["palette", "spotlight"]),
    priority: 92,
  }),
  Object.freeze({
    id: "open-search",
    actionId: "open-search",
    label: "Search: Workspace durchsuchen",
    description: "Finde Text, Dateien und Projektinhalte im Workspace.",
    category: "navigation",
    shortcut: "Ctrl+Shift+F",
    keywords: Object.freeze([
      "find",
      "search",
      "workspace",
      "grep",
      "ripgrep",
      "suche",
      "find in files",
      "content",
      "text",
    ]),
    surfaces: Object.freeze(["palette", "spotlight"]),
    priority: 90,
    favorite: true,
  }),
  Object.freeze({
    id: "focus-editor",
    actionId: "focus-editor",
    label: "Editor fokussieren",
    description: "Springe direkt zur aktiven Editor-Datei.",
    category: "navigation",
    shortcut: "",
    keywords: Object.freeze(["focus", "cursor", "active", "editor", "code"]),
    surfaces: Object.freeze(["palette", "spotlight"]),
    priority: 88,
  }),
  Object.freeze({
    id: "focus-active-symbol",
    actionId: "focus-editor",
    label: "Aktiven Symbol-Scope fokussieren",
    description: "Springe in den Editor und halte Klasse, Methode oder Heading sichtbar.",
    category: "symbols",
    shortcut: "",
    keywords: Object.freeze(["symbol", "symbols", "scope", "breadcrumb", "function", "class", "heading", "active"]),
    surfaces: Object.freeze(["palette", "spotlight"]),
    priority: 86,
  }),
  Object.freeze({
    id: "search-workspace-symbols",
    actionId: "open-search",
    label: "Workspace-Symbole suchen",
    description: "Oeffne die Suche fuer Funktionen, Klassen, Headings und Strukturtreffer.",
    category: "symbols",
    shortcut: "@",
    keywords: Object.freeze(["symbol", "symbols", "outline", "function", "class", "method", "heading", "workspace"]),
    surfaces: Object.freeze(["palette", "spotlight"]),
    priority: 84,
  }),
  Object.freeze({
    id: "github-sync",
    actionId: "github-sync",
    label: "Git: Aenderungen und Branches",
    description: "Pruefe Branch, Staging, Diffs und lokale Aenderungen.",
    category: "source-control",
    shortcut: "",
    keywords: Object.freeze([
      "git",
      "github",
      "source control",
      "scm",
      "commit",
      "stage",
      "staged",
      "unstaged",
      "changes",
      "diff",
      "branch",
      "status",
      "pull",
      "push",
      "sync",
    ]),
    surfaces: Object.freeze(["palette", "spotlight"]),
    priority: 82,
    favorite: true,
  }),
  Object.freeze({
    id: "open-github-issues",
    actionId: "open-github-issues",
    label: "GitHub: Issues und Tasks",
    description: "Oeffne Issues mit Status, Labels und Bearbeitungsaktionen.",
    category: "source-control",
    shortcut: "",
    keywords: Object.freeze(["github", "issues", "bugs", "tasks", "tickets", "triage", "labels"]),
    surfaces: Object.freeze(["palette", "spotlight"]),
    priority: 81,
  }),
  Object.freeze({
    id: "open-pull-requests",
    actionId: "open-pull-requests",
    label: "GitHub: Pull Requests",
    description: "Oeffne PRs, Checks und Review-nahe Aktionen.",
    category: "source-control",
    shortcut: "",
    keywords: Object.freeze(["github", "pull request", "pull requests", "pr", "review", "checks", "ci"]),
    surfaces: Object.freeze(["palette", "spotlight"]),
    priority: 80,
  }),
  Object.freeze({
    id: "open-github-projects",
    actionId: "open-github-projects",
    label: "GitHub: Projects und Boards",
    description: "Oeffne Project Boards und verknuepfte Issues oder PRs.",
    category: "source-control",
    shortcut: "",
    keywords: Object.freeze(["github", "projects", "board", "planning", "project", "roadmap"]),
    surfaces: Object.freeze(["palette"]),
    priority: 79,
  }),
  Object.freeze({
    id: "open-problems",
    actionId: "open-problems",
    label: "Problems: Fehler und Warnungen",
    description: "Oeffne Diagnosemeldungen, Lint-Fehler und Warnungen.",
    category: "diagnostics",
    shortcut: "",
    keywords: Object.freeze([
      "problems",
      "problem",
      "diagnostics",
      "diagnose",
      "errors",
      "warnings",
      "lint",
      "eslint",
      "typescript",
      "ts",
      "quick fix",
    ]),
    surfaces: Object.freeze(["palette", "spotlight"]),
    priority: 80,
    favorite: true,
  }),
  Object.freeze({
    id: "toggle-terminal",
    actionId: "toggle-terminal",
    label: "Terminal: Panel oeffnen",
    description: "Zeige oder fokussiere das integrierte Terminal.",
    category: "terminal",
    shortcut: "Ctrl+`",
    keywords: Object.freeze(["shell", "console", "cli", "terminal", "command line", "integrated terminal"]),
    surfaces: Object.freeze(["palette", "spotlight"]),
    priority: 78,
    favorite: true,
  }),
  Object.freeze({
    id: "terminal-task-runner",
    actionId: "toggle-terminal",
    label: "Terminal: Tasks und Scripts",
    description: "Bereite npm-, Build- oder Test-Tasks im Terminal vor.",
    category: "terminal",
    shortcut: "",
    keywords: Object.freeze([
      "npm",
      "pnpm",
      "yarn",
      "test",
      "build",
      "run",
      "script",
      "scripts",
      "task",
      "tasks",
      "runner",
    ]),
    surfaces: Object.freeze(["palette"]),
    priority: 70,
    favorite: true,
  }),
  Object.freeze({
    id: "toggle-zen",
    actionId: "toggle-zen",
    label: "Zen Mode umschalten",
    description: "Reduziere die Workbench auf fokussiertes Arbeiten.",
    category: "layout",
    shortcut: "Ctrl+K Z",
    keywords: Object.freeze(["focus", "layout", "zen", "distraction", "clean"]),
    surfaces: Object.freeze(["palette", "spotlight"]),
    priority: 74,
  }),
  Object.freeze({
    id: "toggle-sidebar",
    actionId: "toggle-sidebar",
    label: "Sidebar umschalten",
    description: "Blende die seitliche Workbench-Navigation ein oder aus.",
    category: "layout",
    shortcut: "Ctrl+B",
    keywords: Object.freeze(["sidebar", "panel", "left", "workbench", "toggle"]),
    surfaces: Object.freeze(["palette", "spotlight"]),
    priority: 72,
  }),
  Object.freeze({
    id: "layout-balanced",
    actionId: "layout-balanced",
    label: "Layout: Balanced",
    description: "Setze die Workbench auf ein ausgewogenes Layout.",
    category: "layout",
    shortcut: "",
    keywords: Object.freeze(["layout", "balanced", "comfortable", "panels", "workspace"]),
    surfaces: Object.freeze(["palette"]),
    priority: 68,
  }),
  Object.freeze({
    id: "layout-compact",
    actionId: "layout-compact",
    label: "Layout: Compact Focus",
    description: "Gib dem Editor mehr Flaeche fuer konzentrierte Arbeit.",
    category: "layout",
    shortcut: "",
    keywords: Object.freeze(["layout", "compact", "focus", "small", "panels"]),
    surfaces: Object.freeze(["palette"]),
    priority: 66,
  }),
  Object.freeze({
    id: "layout-roomy",
    actionId: "layout-roomy",
    label: "Layout: Roomy",
    description: "Erweitere Panels und Seitenbereiche fuer Uebersicht.",
    category: "layout",
    shortcut: "",
    keywords: Object.freeze(["layout", "roomy", "wide", "large", "panels"]),
    surfaces: Object.freeze(["palette"]),
    priority: 64,
  }),
  Object.freeze({
    id: "cycle-side-panel-size",
    actionId: "cycle-side-panel-size",
    label: "Side Panel Groesse wechseln",
    description: "Wechsle zwischen kompakten und breiten Seitenpanels.",
    category: "layout",
    shortcut: "",
    keywords: Object.freeze(["side", "panel", "size", "width", "layout"]),
    surfaces: Object.freeze(["palette"]),
    priority: 60,
  }),
  Object.freeze({
    id: "cycle-bottom-panel-size",
    actionId: "cycle-bottom-panel-size",
    label: "Bottom Panel Groesse wechseln",
    description: "Wechsle die Hoehe des unteren Workbench-Panels.",
    category: "layout",
    shortcut: "",
    keywords: Object.freeze(["bottom", "panel", "size", "height", "terminal"]),
    surfaces: Object.freeze(["palette"]),
    priority: 58,
  }),
  Object.freeze({
    id: "layout-reset",
    actionId: "layout-reset",
    label: "Layout zuruecksetzen",
    description: "Setze Dock-Zonen, Panelgroessen und Workbench-Preset auf den Nexus Standard zurueck.",
    category: "layout",
    shortcut: "",
    keywords: Object.freeze(["layout", "reset", "dock", "panels", "default", "zuruecksetzen"]),
    surfaces: Object.freeze(["palette", "spotlight"]),
    priority: 57,
  }),
  Object.freeze({
    id: "dock-active-left",
    actionId: "dock-active-left",
    label: "Aktives Panel links docken",
    description: "Verschiebe das aktive Workbench-Panel in die linke Snap-Zone.",
    category: "layout",
    shortcut: "",
    keywords: Object.freeze(["dock", "left", "panel", "snap", "links"]),
    surfaces: Object.freeze(["palette"]),
    priority: 56,
  }),
  Object.freeze({
    id: "dock-active-right",
    actionId: "dock-active-right",
    label: "Aktives Panel rechts docken",
    description: "Verschiebe das aktive Workbench-Panel in die rechte Snap-Zone.",
    category: "layout",
    shortcut: "",
    keywords: Object.freeze(["dock", "right", "panel", "snap", "rechts"]),
    surfaces: Object.freeze(["palette"]),
    priority: 55,
  }),
  Object.freeze({
    id: "dock-active-bottom",
    actionId: "dock-active-bottom",
    label: "Aktives Panel unten docken",
    description: "Verschiebe das aktive Workbench-Panel in die untere Snap-Zone.",
    category: "layout",
    shortcut: "",
    keywords: Object.freeze(["dock", "bottom", "panel", "snap", "unten"]),
    surfaces: Object.freeze(["palette"]),
    priority: 54,
  }),
  Object.freeze({
    id: "open-extensions",
    actionId: "open-extensions",
    label: "Extensions: Erweiterungen verwalten",
    description: "Oeffne Sprachtools, Formatter und Integrationen.",
    category: "extensions",
    shortcut: "",
    keywords: Object.freeze([
      "plugins",
      "extensions",
      "extension",
      "languages",
      "language tools",
      "tools",
      "marketplace",
      "install",
      "enable",
      "disable",
      "prettier",
      "eslint",
    ]),
    surfaces: Object.freeze(["palette", "spotlight"]),
    priority: 76,
    favorite: true,
  }),
  Object.freeze({
    id: "change-theme",
    actionId: "change-theme",
    label: "Settings: Theme und Farben",
    description: "Oeffne die Darstellungseinstellungen.",
    category: "preferences",
    shortcut: "Ctrl+K Ctrl+T",
    keywords: Object.freeze(["appearance", "color", "theme", "dark", "light", "settings"]),
    surfaces: Object.freeze(["palette", "spotlight"]),
    priority: 62,
  }),
  Object.freeze({
    id: "open-settings",
    actionId: "open-settings",
    label: "Settings: Editor konfigurieren",
    description: "Oeffne Editor-, Workspace- und Tastatur-Optionen.",
    category: "preferences",
    shortcut: "Ctrl+,",
    keywords: Object.freeze([
      "preferences",
      "settings",
      "setting",
      "config",
      "configuration",
      "optionen",
      "options",
      "keyboard",
      "shortcuts",
      "workspace settings",
    ]),
    surfaces: Object.freeze(["palette", "spotlight"]),
    priority: 61,
    favorite: true,
  }),
  Object.freeze({
    id: "open-account",
    actionId: "open-account",
    label: "Account anzeigen",
    description: "Oeffne Konto- und Profilinformationen.",
    category: "preferences",
    shortcut: "",
    keywords: Object.freeze(["account", "profile", "user", "konto"]),
    surfaces: Object.freeze(["palette"]),
    priority: 44,
  }),
]);


function normalizeCommandListValue(value) {
  if (Array.isArray(value)) {
    return value.map((item) => String(item || "").trim()).filter(Boolean);
  }
  if (!value) return [];
  return String(value)
    .split(/\s+/)
    .map((item) => item.trim())
    .filter(Boolean);
}

export function getEditorCommandCategory(command) {
  const categoryId = command?.category || "navigation";
  return EDITOR_COMMAND_CATEGORIES[categoryId] || EDITOR_COMMAND_CATEGORIES.navigation;
}

export function normalizeEditorCommand(command, index = 0) {
  const id = String(command?.id || "").trim();
  if (!id) return null;
  const category = getEditorCommandCategory(command);
  return Object.freeze({
    id,
    actionId: String(command?.actionId || id).trim(),
    label: String(command?.label || id).trim(),
    description: String(command?.description || "").trim(),
    category: category.id,
    shortcut: String(command?.shortcut || "").trim(),
    keywords: Object.freeze(normalizeCommandListValue(command?.keywords)),
    surfaces: Object.freeze(normalizeCommandListValue(command?.surfaces || ["palette"])),
    priority: Number.isFinite(Number(command?.priority))
      ? Number(command.priority)
      : Math.max(0, 50 - index),
    favorite: Boolean(command?.favorite),
    extensionId: command?.extensionId ? String(command.extensionId) : "",
  });
}

export function createEditorCommandRegistry(extensionCommands = []) {
  const registry = new Map();
  const safeExtensionCommands = Array.isArray(extensionCommands)
    ? extensionCommands
    : [];
  [...EDITOR_COMMANDS, ...safeExtensionCommands].forEach(
    (command, index) => {
      const normalized = normalizeEditorCommand(command, index);
      if (normalized) registry.set(normalized.id, normalized);
    },
  );

  return Object.freeze(
    [...registry.values()].sort((a, b) => {
      const categoryDelta =
        EDITOR_COMMAND_CATEGORY_ORDER.indexOf(a.category) -
        EDITOR_COMMAND_CATEGORY_ORDER.indexOf(b.category);
      if (categoryDelta !== 0) return categoryDelta;
      if (b.priority !== a.priority) return b.priority - a.priority;
      return a.label.localeCompare(b.label);
    }),
  );
}
