import {
  Code2,
  EyeOff,
  Gauge,
  GitBranch,
  Keyboard,
  Package,
  Palette,
  PanelBottom,
  PanelLeft,
  PanelRight,
  Sparkles,
  Terminal,
  Zap,
} from "lucide-react";
import {
  getBottomPanelSizeOptions,
  getSidePanelSizeOptions,
  getWorkbenchLayoutPresetOptions,
  WORKBENCH_SNAP_ZONES,
} from "../../../pages/editor/workbenchDockModel.js";

export const SETTING_SECTIONS = [
  {
    id: "theme-editor",
    label: "Theme Editor",
    eyebrow: "Design",
    icon: Palette,
    description: "Accent, Glow, Blur, Radius und Editor-Typografie zusammen steuern.",
    keywords: "theme color accent primary glow blur radius roundness editor font minimap diagnostics autocomplete",
  },
  {
    id: "editor",
    label: "Editor",
    eyebrow: "Text",
    icon: Code2,
    description: "Typing, Layout, Hilfen und CodeMirror-Verhalten.",
    keywords: "font line height letter spacing wrap minimap diagnostics autocomplete lsp whitespace cursor bracket tab",
  },
  {
    id: "workbench",
    label: "Workbench",
    eyebrow: "Shell",
    icon: PanelLeft,
    description: "Sidebar, Statusleiste, Zen Mode, Autosave und Panel-Verhalten.",
    keywords: "sidebar visible status bar zen autosave workbench panels background",
  },
  {
    id: "keybindings",
    label: "Keybindings",
    eyebrow: "Shortcuts",
    icon: Keyboard,
    description: "Shortcuts suchen, ueberschreiben, validieren und gezielt zuruecksetzen.",
    keywords: "keyboard shortcuts keybindings commands hotkeys reset conflicts",
  },
  {
    id: "terminal",
    label: "Terminal",
    eyebrow: "Shell",
    icon: Terminal,
    description: "Terminal-Profil und sichere Prozessoptionen.",
    keywords: "terminal shell profile powershell bash cmd process kill",
  },
  {
    id: "git",
    label: "Git/GitHub",
    eyebrow: "Source",
    icon: GitBranch,
    description: "Source-Control und GitHub-Workbench-Defaults.",
    keywords: "git github source control pull requests fetch commit notifications",
  },
  {
    id: "extensions",
    label: "Extensions",
    eyebrow: "Runtime",
    icon: Package,
    description: "Extension-Updates, Empfehlungen und Runtime-Verhalten.",
    keywords: "extensions plugins marketplace recommendations update runtime",
  },
  {
    id: "theme",
    label: "Theme",
    eyebrow: "Presets",
    icon: Sparkles,
    description: "Nexus-Presets, Hintergrund und Farbakzente.",
    keywords: "theme preset background color accent primary secondary",
  },
  {
    id: "performance",
    label: "Performance",
    eyebrow: "Budget",
    icon: Gauge,
    description: "Blur/Glow-Budget, LSP, Diagnostics und Rendering-Kosten.",
    keywords: "performance visual profile blur glow outline lsp diagnostics autocomplete minimap renderer hints budget low power fallback battery",
  },
  {
    id: "animations",
    label: "Animations",
    eyebrow: "Motion",
    icon: Zap,
    description: "Reduced Motion, Cursor-Animationen und Glow-Bewegung.",
    keywords: "animation motion reduce speed duration caret cursor blink glow",
  },
];

export const SETTING_INDEX = [
  {
    id: "primary_accent",
    section: "theme-editor",
    label: "Primaerfarbe",
    description: "Hauptakzent fuer Buttons, Cursor, Selection und Nexus Glow.",
    keywords: "primary accent color colour theme editor",
  },
  {
    id: "secondary_accent",
    section: "theme-editor",
    label: "Sekundaerfarbe",
    description: "Zweiter Akzent fuer Gradients, Switches und dezente Highlights.",
    keywords: "secondary accent color colour theme editor",
  },
  {
    id: "custom_surface",
    section: "theme-editor",
    label: "Custom Surface",
    description: "Panel- und Editor-Oberflaeche als eigener Theme-Wert.",
    keywords: "surface panel background custom color colour theme editor",
  },
  {
    id: "custom_input_surface",
    section: "theme-editor",
    label: "Input Surface",
    description: "Control- und Input-Flaechen fuer Suche, Selects und Felder.",
    keywords: "input control surface field select search custom color colour",
  },
  {
    id: "theme_editor_presets",
    section: "theme-editor",
    label: "Theme Editor Presets",
    description: "Schnelle Rezepte fuer Fokus, Glass und Review-Optik.",
    keywords: "preset recipe apply reset theme editor quick focus glass review",
  },
  {
    id: "theme_export_json",
    section: "theme-editor",
    label: "Export JSON",
    description: "Theme-Editor-Settings und CSS-Tokens in die Zwischenablage kopieren.",
    keywords: "export copy clipboard json theme settings tokens",
  },
  {
    id: "glow_intensity",
    section: "theme-editor",
    label: "Glow Intensitaet",
    description: "Staerke der Akzentbeleuchtung in Panels, Text und Cursor.",
    keywords: "glow bloom neon intensity light",
  },
  {
    id: "glow_radius",
    section: "theme-editor",
    label: "Glow Radius",
    description: "Ausbreitung der Akzentbeleuchtung.",
    keywords: "glow radius bloom light spread",
  },
  {
    id: "panel_blur_strength",
    section: "theme-editor",
    label: "Blur Intensitaet",
    description: "Glass-Blur fuer Settings, Side Panels und Oberflaechen.",
    keywords: "blur glass backdrop performance panel",
  },
  {
    id: "panel_background_mode",
    section: "workbench",
    label: "Panel Background",
    description: "Blur, Fake Glass oder Glass Shader fuer Workbench-Panels.",
    keywords: "panel background blur glass shader workbench",
  },
  {
    id: "ui_radius",
    section: "theme-editor",
    label: "Roundness / Radius",
    description: "Radius fuer die Theme-Vorschau und gespeicherte UI-Rundung.",
    keywords: "radius roundness rounded corner ui",
  },
  {
    id: "font_family",
    section: "editor",
    label: "Editor Font",
    description: "Monospace-Schrift fuer den Code Editor.",
    keywords: "font family typeface editor typography",
  },
  {
    id: "font_size",
    section: "editor",
    label: "Editor Font Size",
    description: "Schriftgroesse in Pixeln.",
    keywords: "font size text zoom editor",
  },
  {
    id: "text_size_preset",
    section: "editor",
    label: "Textgroessen Presets",
    description: "Schnelle Kombinationen aus Font Size, Line Height und Letter Spacing.",
    keywords: "text size font preset scale compact comfortable presentation line height letter spacing",
  },
  {
    id: "line_height",
    section: "editor",
    label: "Line Height",
    description: "Zeilenhoehe im Editor.",
    keywords: "line height spacing editor",
  },
  {
    id: "font_weight",
    section: "editor",
    label: "Schriftstaerke",
    description: "Gewicht der Editor-Schrift.",
    keywords: "font weight bold medium typography",
  },
  {
    id: "letter_spacing",
    section: "editor",
    label: "Letter Spacing",
    description: "Zusatzabstand zwischen Zeichen im Code Editor.",
    keywords: "letter spacing tracking character typografie font editor",
  },
  {
    id: "tab_size",
    section: "editor",
    label: "Tab-Groesse",
    description: "Spaces pro Tab.",
    keywords: "tab size indentation indent spaces",
  },
  {
    id: "word_wrap",
    section: "editor",
    label: "Word Wrap",
    description: "Lange Zeilen umbrechen.",
    keywords: "wrap word line editor",
  },
  {
    id: "line_numbers",
    section: "editor",
    label: "Zeilennummern",
    description: "Line numbers im Gutter anzeigen.",
    keywords: "line numbers gutter editor",
  },
  {
    id: "minimap",
    section: "editor",
    label: "Minimap",
    description: "Kompakte Dateiuebersicht anzeigen, wenn verfuegbar.",
    keywords: "minimap overview code map",
  },
  {
    id: "validation_decorations",
    section: "editor",
    label: "Diagnostics",
    description: "Inline-Diagnostics und Lint-Gutter anzeigen.",
    keywords: "diagnostic validation errors warnings lint problems",
  },
  {
    id: "lsp_enabled",
    section: "editor",
    label: "Autocomplete",
    description: "Language-Server-basierte Vorschlaege, Hover und Diagnose.",
    keywords: "autocomplete completion suggestions lsp hover intellisense",
  },
  {
    id: "lsp_setup",
    section: "editor",
    label: "LSP Setup",
    description: "PATH-Erkennung, Env-Overrides, Install-Hints und Retry-Diagnose je Language Server.",
    keywords: "lsp setup language server path env override install hint retry status diagnostics typescript python rust go clangd",
  },
  {
    id: "autocomplete_enabled",
    section: "editor",
    label: "Autocomplete aktiv",
    description: "CodeMirror-Vorschlaege beim Schreiben und via Shortcut anzeigen.",
    keywords: "autocomplete completion suggestions intellisense active typing",
  },
  {
    id: "autocomplete_lsp",
    section: "editor",
    label: "LSP als Quelle",
    description: "Language Server fuer kontextnahe Vorschlaege nutzen, wenn verfuegbar.",
    keywords: "autocomplete completion lsp language server source",
  },
  {
    id: "autocomplete_snippets",
    section: "editor",
    label: "Snippets",
    description: "Mehrzeilige Vorlagen fuer haeufige Sprachmuster anbieten.",
    keywords: "autocomplete snippets templates boilerplate completion",
  },
  {
    id: "autocomplete_language_hints",
    section: "editor",
    label: "Sprach-Hints",
    description: "Keywords, Standardstrukturen und Framework-nahe Vorschlaege lokal anbieten.",
    keywords: "autocomplete language hints keywords structures local",
  },
  {
    id: "autocomplete_local_words",
    section: "editor",
    label: "Datei-Woerter",
    description: "Woerter und Symbole aus der aktuellen Datei als Vorschlaege verwenden.",
    keywords: "autocomplete local words symbols current document",
  },
  {
    id: "autocomplete_min_chars",
    section: "editor",
    label: "Autocomplete Trigger",
    description: "Wie viele Zeichen getippt werden, bevor Vorschlaege automatisch erscheinen.",
    keywords: "autocomplete trigger min chars delay typing",
  },
  {
    id: "autocomplete_max_items",
    section: "editor",
    label: "Autocomplete Limit",
    description: "Maximale interne Vorschlaege pro Anfrage.",
    keywords: "autocomplete completion limit max suggestions performance",
  },
  {
    id: "render_whitespace",
    section: "editor",
    label: "Whitespace anzeigen",
    description: "Unsichtbare Zeichen markieren.",
    keywords: "whitespace render spaces tabs invisible",
  },
  {
    id: "bracket_colorization",
    section: "editor",
    label: "Klammerfarben",
    description: "Bracket Colorization im Editor.",
    keywords: "bracket colorization parentheses braces colors",
  },
  {
    id: "format_on_paste",
    section: "editor",
    label: "Beim Einfuegen formatieren",
    description: "Format-on-paste fuer unterstuetzte Sprachen.",
    keywords: "format paste formatter editor",
  },
  {
    id: "sticky_scroll",
    section: "editor",
    label: "Sticky Scroll",
    description: "Fixierter Kontext im Editor.",
    keywords: "sticky scroll context editor",
  },
  {
    id: "sidebar_position",
    section: "workbench",
    label: "Sidebar Position",
    description: "Primary activity rail links oder rechts platzieren.",
    keywords: "sidebar workbench rail left right",
  },
  {
    id: "sidebar_visible",
    section: "workbench",
    label: "Sidebar Sichtbarkeit",
    description: "Activity Rail und Side Panel sichtbar halten.",
    keywords: "sidebar visible activity rail panel hide show workbench",
  },
  {
    id: "status_bar_visible",
    section: "workbench",
    label: "Statusleiste",
    description: "Workspace, Sprache und Problemstatus unten anzeigen.",
    keywords: "status bar workbench bottom",
  },
  {
    id: "zen_mode",
    section: "workbench",
    label: "Zen Mode",
    description: "Ablenkungsarme Arbeitsansicht.",
    keywords: "zen focus distraction workbench",
  },
  {
    id: "auto_save",
    section: "workbench",
    label: "Auto Save",
    description: "Lokale Aenderungen automatisch speichern.",
    keywords: "autosave auto save storage",
  },
  {
    id: "workbench_layout_presets",
    section: "workbench",
    label: "Layout Presets",
    description: "Fokus, Comfortable oder Wide direkt anwenden.",
    keywords: "layout preset compact focus comfortable wide quick action shell",
  },
  {
    id: "workbench_panel_sizes",
    section: "workbench",
    label: "Panel Groessen",
    description: "Side-Panel-Breite und Bottom-Dock-Hoehe einstellen.",
    keywords: "panel size width height side bottom dock compact",
  },
  {
    id: "workbench_docking",
    section: "workbench",
    label: "Docking",
    description: "Aktives Panel links, rechts, unten oder hidden docken.",
    keywords: "dock snap left right bottom hidden panel quick action",
  },
  {
    id: "workbench_layout_reset",
    section: "workbench",
    label: "Layout Reset",
    description: "Workbench Layout und Panel-Zonen auf Defaults zuruecksetzen.",
    keywords: "reset layout default fallback restore workbench",
  },
  {
    id: "keybindings_manager",
    section: "keybindings",
    label: "Keybindings Manager",
    description: "Shortcuts suchen, nach Kategorie filtern, Overrides setzen und Konflikte sehen.",
    keywords: "keyboard shortcuts keybindings commands hotkeys override reset conflict categories",
  },
  {
    id: "terminal_default_profile",
    section: "terminal",
    label: "Terminal Default Profile",
    description: "Startprofil fuer neue integrierte Terminals.",
    keywords: "terminal shell profile powershell bash cmd system",
  },
  {
    id: "terminal_confirm_kill",
    section: "terminal",
    label: "Terminal Kill Confirm",
    description: "Vor dem Beenden laufender Terminal-Prozesse bestaetigen.",
    keywords: "terminal process kill confirm safe",
  },
  {
    id: "git_auto_fetch",
    section: "git",
    label: "Git Auto Fetch",
    description: "Repository-Status automatisch im Hintergrund aktualisieren.",
    keywords: "git source control fetch background repository",
  },
  {
    id: "git_smart_commit",
    section: "git",
    label: "Smart Commit",
    description: "Commit-Aktionen fuer gestagte oder eindeutig geaenderte Dateien vorbereiten.",
    keywords: "git commit staged smart changes source control",
  },
  {
    id: "github_pr_notifications",
    section: "git",
    label: "GitHub PR Hinweise",
    description: "Pull-Request- und Review-Signale im GitHub-Panel anzeigen.",
    keywords: "github pull request review notifications prs",
  },
  {
    id: "extensions_auto_update",
    section: "extensions",
    label: "Extension Auto Update",
    description: "Installierte Extensions automatisch aktuell halten, wenn der Runtime-Provider es erlaubt.",
    keywords: "extensions plugins auto update marketplace runtime",
  },
  {
    id: "extensions_recommendations",
    section: "extensions",
    label: "Extension Recommendations",
    description: "Workspace-nahe Extension-Empfehlungen anzeigen.",
    keywords: "extensions recommendations workspace marketplace plugins",
  },
  {
    id: "theme",
    section: "theme",
    label: "Theme Preset",
    description: "Nexus Theme-Familie auswaehlen.",
    keywords: "theme preset palette",
  },
  {
    id: "background",
    section: "theme",
    label: "Hintergrund",
    description: "Theme-Hintergrund oder alternative Presets.",
    keywords: "background wallpaper gradient surface",
  },
  {
    id: "visual_performance_profile",
    section: "performance",
    label: "Performance-Profil",
    description: "Ausbalanciertes Budget fuer Blur, Glow und Animation.",
    keywords: "performance quality balanced profile visual",
  },
  {
    id: "visual_budget_summary",
    section: "performance",
    label: "Visual Budget",
    description: "Sichtbarer Kostenindikator fuer Blur, Glow, Renderer und Motion.",
    keywords: "visual budget cost expensive blur glow renderer motion paint performance",
  },
  {
    id: "low_power_fallback",
    section: "performance",
    label: "Low-Power Fallback",
    description: "Reduzierte Visuals, Motion und Minimap fuer schwache Systeme.",
    keywords: "low power fallback battery reduce motion performance profile minimap",
  },
  {
    id: "glow_renderer",
    section: "performance",
    label: "Glow Renderer",
    description: "CSS oder intensiver Renderpfad fuer Licht.",
    keywords: "glow renderer css three performance",
  },
  {
    id: "panel_glow_outline",
    section: "performance",
    label: "Panel Glow Outline",
    description: "Leuchtende Panel-Kante fuer aktives Theme.",
    keywords: "panel glow outline border light performance",
  },
  {
    id: "reduce_motion",
    section: "animations",
    label: "Reduce Motion",
    description: "Panel-Motion reduzieren und Cursor sanfter deaktivieren.",
    keywords: "reduce motion animation accessibility",
  },
  {
    id: "animations_enabled",
    section: "animations",
    label: "Animationen",
    description: "Mikroanimationen im Settings-Erlebnis ein- oder ausschalten.",
    keywords: "animations motion transition",
  },
  {
    id: "animation_speed",
    section: "animations",
    label: "Animation Speed",
    description: "Tempo der Settings-Transitions und Preview-Bewegung.",
    keywords: "animation speed motion duration transition tempo",
  },
  {
    id: "smooth_caret",
    section: "animations",
    label: "Sanfte Cursor-Animation",
    description: "Cursor-Bewegung und visuelles Effektbudget steuern.",
    keywords: "caret cursor animation smooth",
  },
  {
    id: "animated_typing",
    section: "animations",
    label: "Animated Typing",
    description: "Aktive Zeile beim Schreiben kurz weich hervorheben.",
    keywords: "typing animation write smooth text input pop glow",
  },
  {
    id: "typing_animation_style",
    section: "animations",
    label: "Typing Style",
    description: "Soft, Lift oder Glow fuer den Schreibimpuls.",
    keywords: "typing style soft lift glow animation",
  },
  {
    id: "typing_glow",
    section: "animations",
    label: "Typing Glow",
    description: "Kurzer Lichtimpuls auf der aktiven Schreibzeile.",
    keywords: "typing glow text light active line",
  },
  {
    id: "text_glow",
    section: "animations",
    label: "Text Glow",
    description: "Subtiler Glow auf Editor-Text.",
    keywords: "text glow editor neon light",
  },
  {
    id: "cursor_blinking",
    section: "animations",
    label: "Cursor-Blinken",
    description: "Blinkverhalten im Code Editor.",
    keywords: "cursor blinking blink phase smooth solid",
  },
  {
    id: "cursor_style",
    section: "animations",
    label: "Cursor-Stil",
    description: "Linie, Block oder Unterstrich.",
    keywords: "cursor style line block underline",
  },
  {
    id: "cursor_glow",
    section: "animations",
    label: "Cursor-Glow",
    description: "Leuchtender Cursor im Editor.",
    keywords: "cursor glow caret light",
  },
  {
    id: "icon_glow",
    section: "animations",
    label: "Icon Glow",
    description: "Leuchtende Icons in der Shell.",
    keywords: "icon glow shell light",
  },
];

export const SECTION_IDS = SETTING_SECTIONS.map((section) => section.id);
export const SETTING_INDEX_BY_ID = new Map(SETTING_INDEX.map((entry) => [entry.id, entry]));
export const WORKBENCH_LAYOUT_OPTIONS = getWorkbenchLayoutPresetOptions();
export const WORKBENCH_SIDE_PANEL_SIZE_OPTIONS = getSidePanelSizeOptions();
export const WORKBENCH_BOTTOM_PANEL_SIZE_OPTIONS = getBottomPanelSizeOptions();
export const WORKBENCH_QUICK_ACTION_SETTING_IDS = Object.freeze([
  "workbench_layout_presets",
  "workbench_panel_sizes",
  "workbench_docking",
  "workbench_layout_reset",
]);
export const WORKBENCH_DOCK_ACTIONS = Object.freeze([
  {
    zone: WORKBENCH_SNAP_ZONES.left,
    label: "Links",
    Icon: PanelLeft,
  },
  {
    zone: WORKBENCH_SNAP_ZONES.right,
    label: "Rechts",
    Icon: PanelRight,
  },
  {
    zone: WORKBENCH_SNAP_ZONES.bottom,
    label: "Unten",
    Icon: PanelBottom,
  },
  {
    zone: WORKBENCH_SNAP_ZONES.hidden,
    label: "Hidden",
    Icon: EyeOff,
  },
]);

export const TEXT_SIZE_PRESETS = [
  {
    id: "compact",
    label: "Compact",
    description: "13px / 1.45 fuer dichte Dateien.",
    settings: { font_size: 13, line_height: 1.45, letter_spacing: 0 },
  },
  {
    id: "standard",
    label: "Standard",
    description: "14px / 1.6 als ruhiger Default.",
    settings: { font_size: 14, line_height: 1.6, letter_spacing: 0 },
  },
  {
    id: "comfortable",
    label: "Comfort",
    description: "16px / 1.7 fuer laengere Sessions.",
    settings: { font_size: 16, line_height: 1.7, letter_spacing: 0.02 },
  },
  {
    id: "presentation",
    label: "Present",
    description: "18px / 1.75 fuer Demos und Reviews.",
    settings: { font_size: 18, line_height: 1.75, letter_spacing: 0.04 },
  },
];

export const THEME_EDITOR_SETTING_KEYS = [
  "theme",
  "background",
  "primary_accent",
  "secondary_accent",
  "custom_surface",
  "custom_input_surface",
  "panel_background_mode",
  "glow_renderer",
  "panel_blur_strength",
  "panel_glow_outline",
  "glow_intensity",
  "glow_radius",
  "ui_radius",
  "font_family",
  "font_size",
  "line_height",
  "letter_spacing",
  "font_weight",
  "word_wrap",
  "minimap",
  "validation_decorations",
  "lsp_enabled",
  "reduce_motion",
  "animations_enabled",
  "animation_speed",
  "smooth_caret",
  "animated_typing",
  "typing_animation_style",
  "typing_glow",
  "text_glow",
  "cursor_glow",
  "icon_glow",
  "visual_performance_profile",
];

export const THEME_EDITOR_RECIPES = [
  {
    id: "focus",
    label: "Focus",
    description: "Dichte Code-Ansicht mit wenig Effektkosten.",
    colors: ["#7c8cff", "#38bdf8", "#11141d"],
    settings: {
      custom_surface: "#10131d",
      custom_input_surface: "#151a24",
      panel_background_mode: "blur",
      glow_renderer: "css",
      panel_blur_strength: 10,
      panel_glow_outline: false,
      glow_intensity: 18,
      glow_radius: 10,
      ui_radius: 8,
      animations_enabled: true,
      animation_speed: 0.9,
      visual_performance_profile: "custom",
    },
  },
  {
    id: "glass",
    label: "Glass",
    description: "Mehr Tiefe ohne den intensiven Renderer.",
    colors: ["#8aadf4", "#38bdf8", "#151925"],
    settings: {
      custom_surface: "#111827",
      custom_input_surface: "#182033",
      panel_background_mode: "fake-glass",
      glow_renderer: "css",
      panel_blur_strength: 20,
      panel_glow_outline: true,
      glow_intensity: 34,
      glow_radius: 18,
      ui_radius: 12,
      animations_enabled: true,
      animation_speed: 1,
      visual_performance_profile: "custom",
    },
  },
  {
    id: "review",
    label: "Review",
    description: "Praesenter Look fuer Pairing und Screen-Sharing.",
    colors: ["#f472b6", "#22d3ee", "#17111f"],
    settings: {
      primary_accent: "#f472b6",
      secondary_accent: "#22d3ee",
      custom_surface: "#17111f",
      custom_input_surface: "#22182d",
      panel_background_mode: "fake-glass",
      glow_renderer: "css",
      panel_blur_strength: 18,
      panel_glow_outline: true,
      glow_intensity: 42,
      glow_radius: 20,
      ui_radius: 14,
      font_size: 16,
      line_height: 1.7,
      letter_spacing: 0.02,
      animations_enabled: true,
      animation_speed: 1.05,
      visual_performance_profile: "custom",
    },
  },
];
